export const nigerianStates: Record<string, string[]> = {
  "Abia": ["Aba North", "Aba South", "Umuahia North", "Umuahia South", "Obingwa", "Other"],
  "Adamawa": ["Yola North", "Yola South", "Mubi North", "Mubi South", "Gombi", "Other"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak", "Other"],
  "Anambra": ["Awka North", "Awka South", "Onitsha North", "Onitsha South", "Nnewi North", "Other"],
  "Bauchi": ["Bauchi", "Azare", "Misau", "Ningi", "Tafawa Balewa", "Other"],
  "Bayelsa": ["Yenagoa", "Ogbia", "Sagbama", "Nembe", "Brass", "Other"],
  "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Ogbadibo", "Other"],
  "Borno": ["Maiduguri", "Jere", "Bama", "Biu", "Konduga", "Other"],
  "Cross River": ["Calabar Municipal", "Calabar South", "Ikom", "Ogoja", "Akamkpa", "Other"],
  "Delta": ["Asaba", "Warri South", "Ughelli North", "Sapele", "Uvwie", "Other"],
  "Ebonyi": ["Abakaliki", "Afikpo North", "Afikpo South", "Ezza South", "Ikwo", "Other"],
  "Edo": ["Oredo (Benin City)", "Egor", "Ikpoba Okha", "Esan West", "Etsako West", "Other"],
  "Ekiti": ["Ado Ekiti", "Ikere", "Ijero", "Oye", "Ikole", "Other"],
  "Enugu": ["Enugu East", "Enugu North", "Enugu South", "Nsukka", "Udi", "Other"],
  "FCT - Abuja": ["Abuja Municipal (AMAC)", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Abaji"],
  "Gombe": ["Gombe", "Akko", "Yamaltu/Deba", "Dukku", "Billiri", "Other"],
  "Imo": ["Owerri Municipal", "Owerri North", "Owerri West", "Orlu", "Okigwe", "Other"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim", "Other"],
  "Kaduna": ["Kaduna North", "Kaduna South", "Zaria", "Chikun", "Sabon Gari", "Other"],
  "Kano": ["Kano Municipal", "Dala", "Gwale", "Tarauni", "Nassarawa", "Other"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma", "Other"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega", "Other"],
  "Kogi": ["Lokoja", "Okene", "Idah", "Kabba/Bunu", "Ankpa", "Other"],
  "Kwara": ["Ilorin West", "Ilorin East", "Ilorin South", "Offa", "Ifelodun", "Other"],
  "Lagos": ["Ikeja", "Eti-Osa (Victoria Island/Lekki)", "Lagos Mainland", "Lagos Island", "Alimosho", "Surulere", "Other"],
  "Nasarawa": ["Lafia", "Keffi", "Karu", "Akwanga", "Nasarawa", "Other"],
  "Niger": ["Chanchaga (Minna)", "Bida", "Suleja", "Kontagora", "Shiroro", "Other"],
  "Ogun": ["Abeokuta South", "Abeokuta North", "Ado-Odo/Ota", "Ijebu Ode", "Sagamu", "Other"],
  "Ondo": ["Akure South", "Akure North", "Ondo West", "Owo", "Okitipupa", "Other"],
  "Osun": ["Osogbo", "Olorunda", "Ife Central", "Ilesa West", "Ede North", "Other"],
  "Oyo": ["Ibadan North", "Ibadan South-West", "Egbeda", "Ogbomosho North", "Oyo West", "Other"],
  "Plateau": ["Jos North", "Jos South", "Jos East", "Pankshin", "Shendam", "Other"],
  "Rivers": ["Port Harcourt", "Obio-Akpor", "Eleme", "Bonny", "Oyigbo", "Other"],
  "Sokoto": ["Sokoto North", "Sokoto South", "Wamakko", "Bodinga", "Tambuwal", "Other"],
  "Taraba": ["Jalingo", "Wukari", "Bali", "Sardauna", "Gashaka", "Other"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam", "Other"],
  "Zamfara": ["Gusau", "Tsafe", "Kaura Namoda", "Talata Mafara", "Anka", "Other"]
};